import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import BackgroundLayer from "@/components/BackgroundLayer";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import NavBar from "@/components/pageCompo/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Beyond Sky",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><Providers>

          <div className="min-h-screen  text-white selection:bg-cyan-500/30 selection:text-white">
            <BackgroundLayer />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
